version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"

  frontend:
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8001
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
